Traceback (most recent call last):
  File "/home/jubayer/anaconda3/envs/book-template/lib/python3.7/site-packages/jupyter_cache/executors/basic.py", line 157, in execute
    executenb(nb_bundle.nb, cwd=tmpdirname)
  File "/home/jubayer/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/home/jubayer/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/jubayer/.local/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/jubayer/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(10,6))
# plt.style.use("fivethirtyeight")
# Microbiology
plt.plot(age, mib_salary, label="Microbiology",  color="b", linewidth=2, marker='o')
# Pharmacy
plt.plot(ages, pharma_salary, label= "Pharmacy", color="red", linewidth=3, marker='x')
# BCS
plt.plot(ages, bcs_salary, label= "BCS", linewidth=4, linestyle='--')

plt.xlabel('Ages')
plt.ylabel('Median Salary (USD)')
plt.title('Median Salary (USD) by Age')
plt.legend() 
plt.tight_layout()
plt.show() 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-14-e0bec65d8733>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;31m# plt.style.use("fivethirtyeight")[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;31m# Microbiology[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mage[0m[0;34m,[0m [0mmib_salary[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m"Microbiology"[0m[0;34m,[0m  [0mcolor[0m[0;34m=[0m[0;34m"b"[0m[0;34m,[0m [0mlinewidth[0m[0;34m=[0m[0;36m2[0m[0;34m,[0m [0mmarker[0m[0;34m=[0m[0;34m'o'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;31m# Pharmacy[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0mplt[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mages[0m[0;34m,[0m [0mpharma_salary[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m [0;34m"Pharmacy"[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m"red"[0m[0;34m,[0m [0mlinewidth[0m[0;34m=[0m[0;36m3[0m[0;34m,[0m [0mmarker[0m[0;34m=[0m[0;34m'x'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'age' is not defined
NameError: name 'age' is not defined

